[package]
name = "vcpkg_cli"
version = "0.1.0"
authors = ["mcgoo <mcgoo@users.noreply.github.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/mcgoo/vcpkg-rs"
description = """
A command line utility to investigate which libraries will be
found by the vcpkg Cargo build helper.
"""

[dependencies]
vcpkg = { path = "../vcpkg" }
clap = "2.23.2"
