language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.10.0
script:
  - set RUST_BACKTRACE=1
  - set RUST_TEST_THREADS=1
  - cargo build --manifest-path vcpkg/Cargo.toml --verbose
  - cargo test --manifest-path vcpkg/Cargo.toml --verbose
