language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.10.0
script:
  - export RUST_BACKTRACE=1
  - export RUST_TEST_THREADS=1
  - cargo build --manifest-path vcpkg/Cargo.toml --verbose
  - if [ $TRAVIS_RUST_VERSION != "1.10.0" ] ; then cargo test --manifest-path vcpkg/Cargo.toml --verbose; fi
