#os:
#  - Visual Studio 2015
environment:
  RUST: stable
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      VCPKG_PANIC: 1
      RUSTFLAGS: -Ctarget-feature=+crt-static
      RUST: nightly
      VCPKG_DEFAULT_TRIPLET: x64-windows-static
    - TARGET: x86_64-pc-windows-msvc
      VCPKG_PANIC: 1
      VCPKG_DEFAULT_TRIPLET: x64-windows
    - TARGET: i686-pc-windows-msvc
      VCPKG_PANIC: 1
      RUSTFLAGS: -Ctarget-feature=+crt-static
      RUST: nightly
      VCPKG_DEFAULT_TRIPLET: x86-windows-static
    - TARGET: i686-pc-windows-msvc
      VCPKG_PANIC: 1
      VCPKG_DEFAULT_TRIPLET: x86-windows
    
install:
  # Install Rust
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

  - if defined VCPKG_DEFAULT_TRIPLET git clone https://github.com/Microsoft/vcpkg c:\projects\vcpkg
  - if defined VCPKG_DEFAULT_TRIPLET c:\projects\vcpkg\bootstrap-vcpkg.bat
  - if defined VCPKG_DEFAULT_TRIPLET set VCPKG_ROOT=c:\projects\vcpkg
  - if defined VCPKG_DEFAULT_TRIPLET %VCPKG_ROOT%\vcpkg.exe install sqlite3 libpq libmysql curl zeromq 

build:
  - rustc --version
  - cargo --version
  - set RUST_BACKTRACE=1
  - cargo build --all
  - cargo test --all
  - cargo run --manifest-path vcpkg_cli\Cargo.toml -- probe sqlite3
  - cargo run --manifest-path systest\Cargo.toml 
