[package]
name = "systest"
version = "0.1.0"
authors = ["Jim McGrath <jimmc2@gmail.com>"]

[dependencies]
curl = "*"
libz-sys = "*"
openssl-sys = { git = "https://github.com/mcgoo/rust-openssl", branch = "vcpkg-next" }
zmq-sys = { git = "https://github.com/mcgoo/rust-zmq", branch = "vcpkg-next" }
