[package]
name = "curl_vcpkg_test"
version = "0.1.0"
authors = ["Jim McGrath <jimmc2@gmail.com>"]

[dependencies]
curl = { git = "https://github.com/mcgoo/curl-rust", branch = "vcpkg-next", features = ["use-vcpkg"] }
libz-sys = { git = "https://github.com/alexcrichton/libz-sys" }
openssl-sys = { git = "https://github.com/mcgoo/rust-openssl", branch = "vcpkg-next" }
zmq-sys = { git = "https://github.com/mcgoo/rust-zmq", branch = "vcpkg-next" }

[replace]
"vcpkg:0.2.0" = { path = "../vcpkg" }

#"curl-sys:0.3.10" = { path = "../curl-rust/curl-sys" }
#"libz-sys:1.0.13" = { path = "../libz-sys" }
#"openssl-sys:0.9.11" = { path = "../rust-openssl/openssl-sys" }
#"zmq-sys:0.8.1" = { path = "../rust-zmq/zmq-sys" }
