name: Rust

on: push
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run build
      run: cargo build --manifest-path vcpkg/Cargo.toml --verbose
    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git vcp
        vcp/bootstrap-vcpkg.sh
    - name: Run tests
      run: tests/run.sh
