name: Rust 1.10 compile test

on:
  push:
  pull_request:
  schedule:
    - cron: "35 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set default Rust
        run: rustup default 1.10.0
      - name: Run build
        run: cargo build --manifest-path vcpkg/Cargo.toml --verbose
      - name: Run unit tests
        run: cargo test --manifest-path vcpkg/Cargo.toml --verbose
